# Regresión lineal en Python
## El paquete scikit-learn para regresión lineal y la selección de rasgos

In [2]:
from sklearn.feature_selection import RFE # RFE = Recursive Feature Elimination
from sklearn.svm import SVR # SVM = Support Vector Machine
import pandas as pd
import numpy as np

In [3]:
data = pd.read_csv("../../data/datasets/ads/Advertising.csv")

In [4]:
featured_cols = ["TV", "Radio", "Newspaper"]

In [6]:
X = data[featured_cols] # Variables predictoras
Y = data["Sales"] # Variable de salida

In [7]:
estimator = SVR(kernel="linear") # Modelo lineal
selector = RFE(estimator, 2, step=1) # 2 = variables
selector = selector.fit(X,Y)

In [9]:
selector.support_ # Qué variables fueron seleccionadas para el modelo

array([ True,  True, False])

In [10]:
selector.ranking_

array([1, 1, 2])

In [11]:
from sklearn.linear_model import LinearRegression

In [12]:
X_pred = X[["TV","Radio"]]

In [13]:
lm = LinearRegression()
lm.fit(X_pred, Y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [15]:
lm.intercept_ # Alfa

2.921099912405138

In [18]:
lm.coef_ # Beta

array([0.04575482, 0.18799423])

In [19]:
lm.score(X_pred, Y) # R2 ajustado

0.8971942610828956