# El método de k-means

In [1]:
import numpy as np

In [2]:
data = np.random.random(90).reshape(30,3)
data

array([[0.45025842, 0.69450501, 0.05467647],
       [0.44933376, 0.72587292, 0.28643105],
       [0.58037141, 0.65054973, 0.31306614],
       [0.70730748, 0.8194583 , 0.32755797],
       [0.31747729, 0.73535522, 0.93610665],
       [0.2704705 , 0.0524695 , 0.89305384],
       [0.62233553, 0.04526485, 0.01188222],
       [0.82815707, 0.43829385, 0.27363108],
       [0.00104787, 0.37174969, 0.36483854],
       [0.6068567 , 0.05529723, 0.78087235],
       [0.80003268, 0.38769412, 0.45949239],
       [0.3981952 , 0.95610216, 0.96416601],
       [0.73236133, 0.89248679, 0.08838199],
       [0.09002634, 0.77880339, 0.9079661 ],
       [0.76938085, 0.42862781, 0.97908592],
       [0.36367381, 0.14287881, 0.57031597],
       [0.48384085, 0.70071037, 0.3965248 ],
       [0.51838571, 0.49656341, 0.38707523],
       [0.14625826, 0.76070681, 0.98766308],
       [0.52433621, 0.79067471, 0.19343029],
       [0.00966722, 0.00545688, 0.99761369],
       [0.15075755, 0.20947816, 0.28668199],
       [0.

In [4]:
c1 = np.random.choice(range(len(data))) # Centroide 1
c2 = np.random.choice(range(len(data))) # Centroide 2
clust_centers = np.vstack([data[c1], data[c2]])
clust_centers

array([[0.82815707, 0.43829385, 0.27363108],
       [0.80003268, 0.38769412, 0.45949239]])

In [5]:
from scipy.cluster.vq import vq

In [6]:
vq(data, clust_centers)

(array([0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1,
        1, 1, 1, 0, 0, 1, 1, 1]),
 array([0.50635232, 0.47578637, 0.32864178, 0.40348367, 0.76216081,
        0.76209395, 0.51511821, 0.        , 0.80472996, 0.50108855,
        0.        , 0.85980028, 0.49978524, 0.92639308, 0.52210395,
        0.51246997, 0.44935661, 0.31051857, 0.91952364, 0.47213511,
        1.02973657, 0.69511335, 0.28514166, 0.32438935, 0.59541723,
        0.22097217, 0.55936927, 0.97213727, 0.33641008, 0.35050115]))

In [7]:
from scipy.cluster.vq import kmeans

In [11]:
kmeans(data, clust_centers)

(array([[0.61223005, 0.56377292, 0.26188404],
        [0.33239585, 0.41547798, 0.78238206]]), 0.3796430155371767)

In [12]:
kmeans(data,2)

(array([[0.37185633, 0.43468783, 0.85263157],
        [0.54913272, 0.53163656, 0.26939889]]), 0.3784379293538579)